=head1 NAME

Mail::IMAPClient::Thread - used internally by Mail::IMAPClient->thread

=head1 DESCRIPTION

This module is used internally by L<Mail::IMAPClient> and is 
generated using L<Parse::RecDescent>. It is not meant to be used directly by 
other scripts nor is there much point in debugging it. 

=head1 SYNOPSIS

This module is used internally by L<Mail::IMAPClient> and is not meant to 
be used or called directly from applications. So don't do that.
