#!/usr/bin/perl -w

# $Id: 8859_utf8,v 1.1 2010/10/01 13:00:09 gilles Exp gilles $

use Unicode::MapUTF8 qw(to_utf8 from_utf8 utf8_supported_charset);

die unless (utf8_supported_charset('ISO-8859-1'));

while (<>) {
	print to_utf8({ -string => $_, -charset => 'ISO-8859-1' });
}


