#!/bin/sh

# $Id: memo,v 1.3 2011/03/28 02:14:47 gilles Exp gilles $

echo paypal_bilan_tests_refact_2
paypal_bilan_tests_refact_2() {
# DID output no diff between paypal_bilan_1.22 and 1.23
(
set -x
for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_1.22.out1
	f2=/g/var/paypal_bilan/tests/${fb}_1.22.out2
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.22 \
	  --bnc --debug --debug_csv  "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug --debug_csv  "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_tva.out1
	f2=/g/var/paypal_bilan/tests/${fb}_tva.out2
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.22 \
	   "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	   "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done



)
}



#echo paypal_bilan_tests_refact_1
paypal_bilan_tests_refact_1() {
# DID output no diff between paypal_bilan_1.11 and 1.13
(
#set -x
for f in /g/paypal/paypal_201?_??.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/$fb.out1
	f2=/g/var/paypal_bilan/tests/$fb.out2
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.11 \
	  --bnc --debug  "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug  "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/$fb.out1
	f2=/g/var/paypal_bilan/tests/$fb.out2_usd_eur
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.11 \
	  --bnc --debug  "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug --usdeur 1.2981 "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??.csv; do
	fb=`basename "$f" .csv`

	#echo $fb

	f1i=/g/paypal/$fb.csv
	f2i=/g/paypal/${fb}_complet.csv

	f1o=/g/var/paypal_bilan/tests/t03_$fb.out1
	f2o=/g/var/paypal_bilan/tests/t03_$fb.out2

	#echo $f1i
	#echo $f2i
	#echo $f1o
	#echo $f2o

	rm -f "$f1o" "$f2o"
	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug  "$f1i" \
	> "$f1o"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug  "$f2i" \
	> "$f2o"

	echo diff "$f1o" "$f2o"
	diff "$f1o" "$f2o"
done
)
}

#echo paypal_bilan_tests_dev
paypal_bilan_tests_dev() {

/g/public_html/imapsync/paypal_reply/paypal_bilan \
 /g/paypal/paypal_201?_??_complet.csv --invoices '1 50  200'
	
# Strange characters
/g/public_html/imapsync/paypal_reply/paypal_bilan \
  /g/paypal/paypal_201?_??_complet.csv --invoices '389 234 96'

# France 
/g/public_html/imapsync/paypal_reply/paypal_bilan \
  /g/paypal/paypal_201?_??_complet.csv --invoices '9 392'

# individual
/g/public_html/imapsync/paypal_reply/paypal_bilan \
  /g/paypal/paypal_201?_??_complet.csv --invoices '313 415'

# /g/public_html/imapsync/paypal_reply/paypal_bilan  /g/paypal/paypal_2011_03_complet.csv
# pb with latex
#     Ok 10 # character
# 65  clientAdrB Keyboard character used is undefined YOSHITO YONEI
#     Ok 84 Missing $ inserted. clientEmail victor_su@yahoo.com
# 92 Dr. Westernacher & Partner GmbH

# /g/public_html/imapsync/paypal_reply/paypal_bilan  --first_in 147 --invoices '242'   /g/paypal/paypal_2010_1?_complet.csv
}
