#!/bin/sh

# $Id: paypal_run_laposte,v 1.3 2011/03/23 17:02:39 gilles Exp $

set -e
#set -x


# Add path to commands at home
PATH=$PATH:/g/public_html/imapsync/paypal_reply
PERL5LIB=/g/public_html/imapsync/Mail-IMAPClient-3.28/lib
export PERL5LIB

test -f /g/public_html/imapsync/paypal_reply/paypal_functions \
&& . /g/public_html/imapsync/paypal_reply/paypal_functions


DATE_1=`date`

echo "==== paypal_reply_laposte ===="
paypal_reply_laposte "$@"
echo



DATE_2=`date`

echo "Debut : $DATE_1" 
echo "Fin   : $DATE_2"
echo "Yo Bery GOOD !"
