--- #YAML:1.0
name:                Mail-IMAPClient
version:             2.99_02
abstract:            IMAP4 client library
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Carp:                          0
    Data::Dumper:                  0
    Digest::HMAC_MD5:              0
    Errno:                         0
    Fcntl:                         0
    File::Temp:                    0.18
    IO::File:                      0
    IO::Select:                    0
    IO::Socket:                    0
    IO::Socket::INET:              1.26
    MIME::Base64:                  0
    Parse::RecDescent:             1.94
    Test::More:                    0
    Test::Pod:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
