#!/bin/sh

# $Id: check_win64err,v 1.1 2019/02/18 12:01:21 gilles Exp gilles $

test -n "$1" || { echo usage: "$0 script.bat" && exit 1 ; }

test -d W/LOG_bat || mkdir W/LOG_bat
ERROR_FILENAME=$1.txt
rm -f "W/LOG_bat/$ERROR_FILENAME"
if scp pc_HP_DV7_p24:'Desktop/imapsync_build/LOG_bat/'"$ERROR_FILENAME" W/LOG_bat/ > /dev/null 2>&1 ; then
        #echo -n "W/LOG_bat/$ERROR_FILENAME : "
        #cat "W/LOG_bat/$ERROR_FILENAME"
        sed -e "s#^#W/LOG_bat/$ERROR_FILENAME : #" "W/LOG_bat/$ERROR_FILENAME"
        exit 1
else 
        echo NO errror
fi
