#!/bin/sh

docker_pull_count()
{
    curl -s https://hub.docker.com/v2/repositories/gilleslamiral/imapsync/ | jq '.pull_count'
}

docker_pull_count >> /home/gilles/public_html/imapsync/W/docker_pull_count.txt


