#!/usr/bin/perl


use Unicode::IMAPUtf7;

my $t = Unicode::IMAPUtf7->new();

while (<>) {
	chomp ;
	#push( @result, sprintf( "%33s %s\n", $_, $t->decode($_) ) ) ;
	push( @result, sprintf( "%s\n", $t->decode($_) ) ) ;
}

print @result ;
