#!/usr/bin/perl 

use strict ;
use warnings ;
use Encode::IMAPUTF7 ;

sub imap_utf7_decode_new
{
        use utf8 ;
        my ( $s ) = shift ;
        return( Encode::IMAPUTF7::decode("IMAP-UTF-7", $s ) ) ;
}

sub imap_utf7_encode_new
{
        use utf8 ;
        my ( $s ) = shift ;
        return( Encode::IMAPUTF7::encode("IMAP-UTF-7", $s ) ) ;
}

#use utf8 ;
while ( <> ) 
{
        chomp ;
        #print( Encode::IMAPUTF7::encode('IMAP-UTF-7', $_ ), "\n" ) ;
        print( Encode::IMAPUTF7::decode('IMAP-UTF-7', $_ ), "\n" ) ;
}
