#!/bin/sh


# Generate messages with line lenght from 10 ... up to 99 characters
for M in `count 10 99`; do 
	echo $M
	{ echo Hello Guys; echo ; perl -e "print 'L' x ${M}" ; echo; echo END; }  
done

