#!/bin/sh

# $Id: longline_10000_11000,v 1.2 2014/01/15 02:21:38 gilles Exp gilles $

# Test Exchange limit for maxlinelenght
# Generate messages with line lenght of 10000 10100 ... up to 10990 characters
for M in `count 10 99`; do 
	echo $M
	{ echo Hello Guys; echo ; perl -e "print 'L' x 10${M}0" ; echo; echo END; }  \
	| mail.mailutils -s "line of 10${M}0 characters" tata@localhost.
done

