#!/usr/bin/perl

# $Id: perlcritic_ProhibitInterpolationOfLiterals,v 1.3 2016/06/15 22:18:23 gilles Exp gilles $

use strict;
use warnings;

our $VERSION = q$Revision: 1.3 $;

if ( "\1foo" eq '\1foo' ) {
    print "equal\n";
}
else {
    print "not equal\n";
}

