#!/usr/bin/perl

use strict ;
use warnings ;

print "123456789\\" ."\n" ;
print '123456789\\' ."\n" ;
print "123456789\"" ."\n" ;
print '123456789\'' ."\n" ;

print "\\" ."\n" ;
print q{\\} ."\n" ;

print qq{ !"#$%&'()*+,-./0123456789:;<=>?\@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefg\n} ;

print "\1auth=Bearer " . "\1\1" . "\n" ;
print '\1auth=Bearer ' . '\1\1' . "\n" ;

if ( "\1foo" eq '\1foo' ) {
	print "equal\n" ;
}else{
	print "not equal\n" ;
}

