#!/usr/bin/perl -w


if ( not( grep /\b\\Noselect\b/i, ('* LIST (\Noselect \HasChildren) "/" Archive') ) ) {
	print "Selectable\n" ;
}else{
	print "Not selectable\n" ;
}


if ( not( grep /\\Noselect\b/i, ('* LIST (\Noselect \HasChildren) "/" Archive') ) ) {
	print "Selectable\n" ;
}else{
	print "Not selectable\n" ;
}
