#!/usr/bin/perl -w

my $f_sep = $ARGV[0] || "/";
my $t_sep = $ARGV[1] || ".";
my $o_sep = "\000";

foreach my $f_fold ("testsub/testsub3", "testsub.testsub3", "a.b/c.d/e" ) {
	my $t_fold;
	print "From Folder [$f_fold]\n";
	$t_fold = $f_fold;
	my $t_fold2 = $t_fold3 = $f_fold;
	
	$t_fold  =~ s¤\Q$f_sep¤$t_sep¤g;
	$t_fold2 =~ s¤\Q$t_sep¤$f_sep¤g;
	$t_fold3 =~ s¤\Q$t_sep¤$o_sep¤g;
	$t_fold4 =  $t_fold3;
	$t_fold4 =~ s¤\Q$f_sep¤$t_sep¤g;
	$t_fold5 =  $t_fold4;
	$t_fold5 =~ s¤\Q$o_sep¤$f_sep¤g;
	
	#$t_fold =~ s¤/¤.¤g;
	print "To $f_sep$t_sep /.  Folder [$t_fold]\n";
	print "To $t_sep$f_sep ./  Folder2[$t_fold2]\n";
	print "To $t_sep"."0 .0  Folder3[$t_fold3]\n";
	print "To $f_sep$t_sep of .0  Folder4[$t_fold4]\n";
	print "To 0$f_sep 0/  Folder5[$t_fold5]\n\n";
}
