#!/bin/sh

# $Id: memo,v 1.5 2011/05/20 12:57:31 gilles Exp gilles $


echo paypal_bilan_tests_invoice
paypal_bilan_tests_invoice() {
# DID output no diff between paypal_bilan_1.43 and 1.??
(
#set -x
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.44 --bnc --debug --debug_invoice --first_in 147 --avoid_numbers '292 293  643 644 731 732 1093 1330 1331 1332 1333 1334' /g/paypal/paypal_201?_??_complet.csv \
 > /g/var/paypal_bilan/tests/paypal_invoice.out1 2>&1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --debug_invoice --first_in 147 --avoid_numbers '292 293  643 644 731 732 1093 1330 1331 1332 1333 1334' /g/paypal/paypal_201?_??_complet.csv \
 > /g/var/paypal_bilan/tests/paypal_invoice.out2 2>&1

echo diff /g/var/paypal_bilan/tests/paypal_invoice.out1 /g/var/paypal_bilan/tests/paypal_invoice.out2
     diff /g/var/paypal_bilan/tests/paypal_invoice.out1 /g/var/paypal_bilan/tests/paypal_invoice.out2
)
}


#echo paypal_bilan_tests_Etat_Province
paypal_bilan_tests_Etat_Province() {
# DID output no diff between paypal_bilan_1.41 and 1.42
(
#set -x
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.41 --bnc --debug --first_in 147 --avoid_numbers '292 293  643 644 731 732 1093 1330 1331 1332 1333 1334' /g/paypal/paypal_201?_??_complet.csv \
 > /g/var/paypal_bilan/tests/paypal_Etat_Province.out1 2>&1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 147 --avoid_numbers '292 293  643 644 731 732 1093 1330 1331 1332 1333 1334' /g/paypal/paypal_201?_??_complet.csv \
 > /g/var/paypal_bilan/tests/paypal_Etat_Province.out2 2>&1
echo diff /g/var/paypal_bilan/tests/paypal_Etat_Province.out1 /g/var/paypal_bilan/tests/paypal_Etat_Province.out2
diff /g/var/paypal_bilan/tests/paypal_Etat_Province.out1 /g/var/paypal_bilan/tests/paypal_Etat_Province.out2
)
}

#echo paypal_bilan_tests_refact_4
paypal_bilan_tests_refact_4() {
# DID output no diff between paypal_bilan_1.33 and 1.??
(
#set -x

# from 147 to 213
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 147 /g/paypal/paypal_2010_11_complet.csv > /g/var/paypal_bilan/tests/paypal_2010_11_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 147 /g/paypal/paypal_2010_11_complet.csv > /g/var/paypal_bilan/tests/paypal_2010_11_complet.csv.1.33_first_in.out2
echo diff /g/var/paypal_bilan/tests/paypal_2010_11_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2010_11_complet.csv.1.33_first_in.out2
diff /g/var/paypal_bilan/tests/paypal_2010_11_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2010_11_complet.csv.1.33_first_in.out2

# from 214 to 291
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 214 /g/paypal/paypal_2010_12_complet.csv > /g/var/paypal_bilan/tests/paypal_2010_12_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 214 /g/paypal/paypal_2010_12_complet.csv > /g/var/paypal_bilan/tests/paypal_2010_12_complet.csv.1.33_first_in.out2
echo diff /g/var/paypal_bilan/tests/paypal_2010_12_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2010_12_complet.csv.1.33_first_in.out2
diff /g/var/paypal_bilan/tests/paypal_2010_12_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2010_12_complet.csv.1.33_first_in.out2

# from 294 to 381
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 294 /g/paypal/paypal_2011_01_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 294 /g/paypal/paypal_2011_01_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out2
echo diff  /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out2
diff  /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out2

/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 292 --avoid_numbers '292 293' /g/paypal/paypal_2011_01_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out3
echo diff  /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out3
diff  /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_01_complet.csv.1.33_first_in.out3

# from 382 to 472
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 382 /g/paypal/paypal_2011_02_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_02_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 382 /g/paypal/paypal_2011_02_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_02_complet.csv.1.33_first_in.out2
echo diff /g/var/paypal_bilan/tests/paypal_2011_02_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_02_complet.csv.1.33_first_in.out2
diff /g/var/paypal_bilan/tests/paypal_2011_02_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_02_complet.csv.1.33_first_in.out2

# from 473 to 569
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 473 /g/paypal/paypal_2011_03_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_03_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 473 /g/paypal/paypal_2011_03_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_03_complet.csv.1.33_first_in.out2
echo diff /g/var/paypal_bilan/tests/paypal_2011_03_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_03_complet.csv.1.33_first_in.out2
diff /g/var/paypal_bilan/tests/paypal_2011_03_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_03_complet.csv.1.33_first_in.out2

# from 570 to 642
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 570 /g/paypal/paypal_2011_04_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_04_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 570 /g/paypal/paypal_2011_04_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_04_complet.csv.1.33_first_in.out2
echo diff /g/var/paypal_bilan/tests/paypal_2011_04_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_04_complet.csv.1.33_first_in.out2
diff /g/var/paypal_bilan/tests/paypal_2011_04_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_04_complet.csv.1.33_first_in.out2

# from 645 to 730
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 645 /g/paypal/paypal_2011_05_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_05_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 645 /g/paypal/paypal_2011_05_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_05_complet.csv.1.33_first_in.out2
echo diff /g/var/paypal_bilan/tests/paypal_2011_05_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_05_complet.csv.1.33_first_in.out2
diff /g/var/paypal_bilan/tests/paypal_2011_05_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_05_complet.csv.1.33_first_in.out2

# from 733 to 764
/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 --bnc --debug --first_in 733 /g/paypal/paypal_2011_06_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out1
/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 733 /g/paypal/paypal_2011_06_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out2
echo diff  /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out2
diff  /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out2

/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 733 --avoid_numbers '' \
  /g/paypal/paypal_2011_06_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out3
echo diff  /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out3
diff  /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out3

/g/public_html/imapsync/W/paypal_reply/paypal_bilan      --bnc --debug --first_in 731 --avoid_numbers '731 732' \
  /g/paypal/paypal_2011_06_complet.csv > /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out4
echo diff  /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out4
diff  /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out1 /g/var/paypal_bilan/tests/paypal_2011_06_complet.csv.1.33_first_in.out4


for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_1.32.out1
	f2=/g/var/paypal_bilan/tests/${fb}_1.32.out2
	rm "$f2"
	/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 \
	  --bnc --debug --debug_csv  "$f" \
	> "$f1"

	/g/public_html/imapsync/W/paypal_reply/paypal_bilan \
	  --bnc --debug --debug_csv  "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_tva.out1
	f2=/g/var/paypal_bilan/tests/${fb}_tva.out2
	rm "$f2"
	/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.33 \
	   "$f" \
	> "$f1"

	/g/public_html/imapsync/W/paypal_reply/paypal_bilan \
	   "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

)
}


#echo paypal_bilan_tests_refact_3
paypal_bilan_tests_refact_3() {
# DID output no diff between paypal_bilan_1.27 and 1.??
(
#set -x
for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_1.27.out1
	f2=/g/var/paypal_bilan/tests/${fb}_1.27.out2
	rm "$f2"
	/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.27 \
	  --bnc --debug --debug_csv  "$f" \
	> "$f1"

	/g/public_html/imapsync/W/paypal_reply/paypal_bilan \
	  --bnc --debug --debug_csv  "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_tva.out1
	f2=/g/var/paypal_bilan/tests/${fb}_tva.out2
	rm "$f2"
	/g/public_html/imapsync/W/paypal_reply/paypal_bilan_1.27 \
	   "$f" \
	> "$f1"

	/g/public_html/imapsync/W/paypal_reply/paypal_bilan \
	   "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done
)
}


#echo paypal_bilan_tests_refact_2
paypal_bilan_tests_refact_2() {
# DID output no diff between paypal_bilan_1.22 and 1.23
(
set -x
for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_1.22.out1
	f2=/g/var/paypal_bilan/tests/${fb}_1.22.out2
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.22 \
	  --bnc --debug --debug_csv  "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug --debug_csv  "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??_complet.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/${fb}_tva.out1
	f2=/g/var/paypal_bilan/tests/${fb}_tva.out2
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.22 \
	   "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	   "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done
)
}



#echo paypal_bilan_tests_refact_1
paypal_bilan_tests_refact_1() {
# DID output no diff between paypal_bilan_1.11 and 1.13
(
#set -x
for f in /g/paypal/paypal_201?_??.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/$fb.out1
	f2=/g/var/paypal_bilan/tests/$fb.out2
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.11 \
	  --bnc --debug  "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug  "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??.csv; do
	fb=`basename "$f"`
	f1=/g/var/paypal_bilan/tests/$fb.out1
	f2=/g/var/paypal_bilan/tests/$fb.out2_usd_eur
	rm "$f2"
	/g/public_html/imapsync/paypal_reply/paypal_bilan_1.11 \
	  --bnc --debug  "$f" \
	> "$f1"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug --usdeur 1.2981 "$f" \
	> "$f2"

	echo diff "$f1" "$f2"
	diff "$f1" "$f2"
done

for f in /g/paypal/paypal_201?_??.csv; do
	fb=`basename "$f" .csv`

	#echo $fb

	f1i=/g/paypal/$fb.csv
	f2i=/g/paypal/${fb}_complet.csv

	f1o=/g/var/paypal_bilan/tests/t03_$fb.out1
	f2o=/g/var/paypal_bilan/tests/t03_$fb.out2

	#echo $f1i
	#echo $f2i
	#echo $f1o
	#echo $f2o

	rm -f "$f1o" "$f2o"
	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug  "$f1i" \
	> "$f1o"

	/g/public_html/imapsync/paypal_reply/paypal_bilan \
	  --bnc --debug  "$f2i" \
	> "$f2o"

	echo diff "$f1o" "$f2o"
	diff "$f1o" "$f2o"
done
)
}

#echo paypal_bilan_tests_dev
paypal_bilan_tests_dev() {

/g/public_html/imapsync/paypal_reply/paypal_bilan \
 /g/paypal/paypal_201?_??_complet.csv --invoices '1 50  200'
	
# Strange characters
/g/public_html/imapsync/paypal_reply/paypal_bilan \
  /g/paypal/paypal_201?_??_complet.csv --invoices '389 234 96'

# France 
/g/public_html/imapsync/paypal_reply/paypal_bilan \
  /g/paypal/paypal_201?_??_complet.csv --invoices '9 392'

# individual
/g/public_html/imapsync/paypal_reply/paypal_bilan \
  /g/paypal/paypal_201?_??_complet.csv --invoices '313 415'

# /g/public_html/imapsync/paypal_reply/paypal_bilan  /g/paypal/paypal_2011_03_complet.csv
# pb with latex
#     Ok 10 # character
# 65  clientAdrB Keyboard character used is undefined YOSHITO YONEI
#     Ok 84 Missing $ inserted. clientEmail victor_su@yahoo.com
# 92 Dr. Westernacher & Partner GmbH

# /g/public_html/imapsync/paypal_reply/paypal_bilan  --first_in 147 --invoices '242'   /g/paypal/paypal_2010_1?_complet.csv
}
