#!/bin/sh

# $Id: paypal_run_dev,v 1.5 2011/05/20 10:50:05 gilles Exp gilles $

set -e
#set -x

# Add path to commands at home
PATH=$PATH:/g/public_html/imapsync/W/paypal_reply
PERL5LIB=/g/public_html/imapsync/Mail-IMAPClient-3.30/lib
export PERL5LIB

test -f /g/public_html/imapsync/W/paypal_reply/paypal_functions \
&& . /g/public_html/imapsync/W/paypal_reply/paypal_functions

DATE_1=`date`

echo "==== paypal_reply_test ===="
paypal_reply_petite_dev "$@" 
echo

DATE_2=`date`

echo "Debut : $DATE_1" 
echo "Fin   : $DATE_2"
echo "Yo Bery GOOD !"
