#!/bin/sh

# $Id: paypal_run_laposte,v 1.8 2015/03/09 17:48:48 gilles Exp gilles $

set -e
#set -x

# Add path to commands at home
PATH=$PATH:/g/public_html/imapsync/W/paypal_reply
PERL5LIB=/g/public_html/imapsync/W/Mail-IMAPClient-3.35/lib
export PERL5LIB

test -f /g/public_html/imapsync/W/paypal_reply/paypal_functions \
&& . /g/public_html/imapsync/W/paypal_reply/paypal_functions


DATE_1=`date`

echo "==== paypal_reply_laposte ===="
paypal_reply_laposte "$@"
echo



DATE_2=`date`

echo "Debut : $DATE_1" 
echo "Fin   : $DATE_2"
echo "Yo Bery GOOD !"
