#!/usr/bin/perl 

# $Id: paypal_build_reply,v 1.33 2017/07/03 22:49:06 gilles Exp gilles $

use warnings;
use strict;
use Getopt::Long;

my ($msg_id_file, $msg_id);
my ($amount, $name, $email);
my (
	$paypal_line, $paypal_info,
	$buyer, $description, $object, 
	$release, $release_exe, 
);

my $help ;
my $debug ;

my $numopt = scalar(@ARGV);
my $opt_ret = GetOptions(
        "help"          => \$help,
        "debug!"        => \$debug,
);

usage(  ) and exit if ( $help or ! $numopt ) ;

$msg_id_file = $ARGV[1];
$msg_id = firstline($msg_id_file);

$release      = firstline( '/g/public_html/imapsync/VERSION' ) ;
$release_exe  = firstline( '/g/public_html/imapsync/VERSION_EXE' ) ;
#my $path_last = firstline( '/g/public_html/imapsync/dist/path_last.txt' ) ;


$debug and print "Hi!\n" ;

my @input = <> ;

while( my $line = shift @input ) {
	next if ( $line !~ /^(.*de transaction.*)$/ );
	$paypal_line = $1;
	$paypal_info  = "===== Paypal id =====\n$paypal_line\n";
	$debug and print "$paypal_info" ;
	last;
}
while( my $line = shift @input ) {
	if ( $line =~ /^Vous avez re.*paiement d'un montant de (.*) de la part de (.*) ?\((.*)\)/) {
		($amount, $name, $email) = ($1, $2, $3);
                $debug and print "1 ($amount, $name, $email)\n" ;
		last;
	}
	if ( $line =~ /^Vous avez re.*paiement d'un montant de (.*) de la part de (.*)/) {
		($amount, $name, $email) = ($1, "", $2);
                $debug and print "2 ($amount, $name, $email)\n" ;
		last;
	}
}


$debug and print "[$amount] [$name] [$email] [$paypal_line]\n";

$amount =~ /^.*?(\d+.*)/ ;
my $amount_ascii = $1 || '' ;

while( my $line = shift @input ) {
	if ( $line =~ /^Acheteur/ ) {
		$buyer .= "===== Acheteur =====\n";
                $debug and print "1 $buyer\n" ;
		last;
	}
	if ( $line =~ /^Informations sur l'acheteur/ ) {
		$buyer .= "===== Acheteur =====\n";
		chomp( $name = shift @input );
		$buyer .= "$name\n" ;
                $debug and print "2 $buyer\n" ;
		last;
	}
	if ( $line =~ /^"Informations sur l'acheteur :"/ ) {
		$buyer .= "===== Acheteur =====\n";
		shift @input ;
		chomp( $name = shift @input );
		$buyer .= "$name\n" ;
                $debug and print "2 $buyer\n" ;
		last;
	}
	
}

while( my $line = shift @input ) {
      $buyer .= $line if ( ( $line !~ /^-----------------------------------/ ) and ( $line !~ /^Veuillez conserver ce num/ ) );
      last if ( ( $line =~ /^-----------------------------------/ ) or ( $line =~ /^Veuillez conserver ce num/ ) or ( $line =~ /tails de l'achat/)  ) ;
}
$debug and print "3 $buyer\n" ;

while( my $line = shift @input ) {
	$debug and print "Search Description [$line]\n" ;
	next if ( $line !~ /Description..?:(.*)/ ) ;
        $object = $1 ;
	$description  = "===== Details =====\n" ;
	$description .= $line ;
	last ;
}
$debug and print "[$object] [$description]\n" ;


while( my $line = shift @input ) {
	$debug and print "LINE:$line" ;
	$description .= $line;
	last if ( $line =~ /^Paiement envoy/ );
	last if ( $line =~ /^N.*d'avis de r.*ception/ );
}


my $address = 'gilles.lamiral@laposte.net';
my $address2 = 'gilles@lamiral.info';
my $rcstag  = '$Id: paypal_build_reply,v 1.33 2017/07/03 22:49:06 gilles Exp gilles $';

my $contact = 
q{
For imapsync professional support or any other request,
contact me (Gilles LAMIRAL) by email or phone at:

Email address:              gilles.lamiral@laposte.net
Mobile phone number:        +33 6 19 22 03 54 (France, SFR operator)
Professionnal phone number: +33 9 51 84 42 42 (France, Free operator) 
} ;

my $download_info = 
qq{
Software users, you will find the latest stable imapsync software 
(release $release) at the following link:
https://imapsync.lamiral.info/dist/
Next imapsync releases will be available to you for lifetime without 
extra payment. To know if a new release is available, just
run imapsync with no arguments or look at the end of any logfile.
} ;

my $online_info =
q{
Online users, the imapsync service is at
https://imapsync.lamiral.info/X/
Don't hesitate to drop me a note in case of problems or
clarifications about this online visual interface.
} ;

my $newsletter =
q{
As a buyer, you are also subscribed to a very low traffic newsletter 
called [imapsync_update], announcing new releases or new services. 
You might have reveived a welcome email message from the list manager, 
telling you how to unsubscribe by yourself at
http://lists.lamiral.info/cgi-bin/mailman/listinfo/imapsync_update
In any case, you can also ask me to unsubscribe you, as
it's often frustrating to deal with unsubscriptions.

} ;


my $thanks = 
q{
I thank you for buying and using imapsync services or products,
I wish you very successful transfers!

You will receive an invoice soon.
} ;

my $text = $thanks 
. $contact 
. $download_info
. $online_info
. $newsletter
;

my $subject = "[imapsync download/support/online] imapsync payment done [$amount_ascii from $email]" ;



my $message = <<EOM
X-Comment: $rcstag
In-Reply-To: $msg_id
From: Gilles LAMIRAL <$address>
To: <$email>
Cc: Gilles LAMIRAL <$address>, <$address2>
Subject: $subject

Hello $name,

$text

$paypal_info
$buyer
$description
==== Vendeur ====
Gilles LAMIRAL
La Billais
35580 Baulon
FRANCE

Tel: +33 9 51 84 42 42
Mob: +33 6 19 22 03 54
Fax: +33 9 56 84 42 42

email: $address

-- 
Au revoir,
Gilles Lamiral.
EOM
;

=pod
=cut


print $message;
$debug and print "[$amount] [$name] [$email] [$paypal_line] [$object]\n";


sub firstline {
        # extract the first line of a file (without \n)

        my($file) = @_;
        my $line  = "";
        
        open FILE, $file or die("error [$file]: $! ");
        chomp($line = <FILE>);
        close FILE;
        $line = ($line) ? $line: "error !EMPTY! [$file]";
        return $line;
}

sub usage {
	print "$0\n" ;
}
