#!/bin/sh

# $Id: paypal_build_invoices,v 1.139 2017/09/09 19:31:54 gilles Exp gilles $

# usage: sh paypal_build_invoices  /g/var/paypal_invoices/????

lyx -e latex /home/gilles/public_html/AGIL/factures/000/facture_imapsync-000.lyx
cp /home/gilles/public_html/AGIL/factures/000/facture_imapsync-000.tex /g/var/paypal_invoices/

#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 147 /g/paypal/paypal_2010_11_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 214 /g/paypal/paypal_2010_12_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 294 /g/paypal/paypal_2011_01_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 382 /g/paypal/paypal_2011_02_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 473 /g/paypal/paypal_2011_03_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 570 /g/paypal/paypal_2011_04_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 645 /g/paypal/paypal_2011_05_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 733 /g/paypal/paypal_2011_06_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 824 /g/paypal/paypal_2011_07_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 917 /g/paypal/paypal_2011_08_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 999 /g/paypal/paypal_2011_09_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1094 /g/paypal/paypal_2011_10_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1185 /g/paypal/paypal_2011_11_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1263 /g/paypal/paypal_2011_12_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1335 /g/paypal/paypal_2012_01_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1417 /g/paypal/paypal_2012_02_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1508 /g/paypal/paypal_2012_03_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1575 /g/paypal/paypal_2012_04_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1654 /g/paypal/paypal_2012_05_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1743 /g/paypal/paypal_2012_06_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1824 /g/paypal/paypal_2012_07_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1891 /g/paypal/paypal_2012_08_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 1963 /g/paypal/paypal_2012_09_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2047 /g/paypal/paypal_2012_10_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2133 /g/paypal/paypal_2012_11_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2224 /g/paypal/paypal_2012_12_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2299 /g/paypal/paypal_2013_01_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2384 /g/paypal/paypal_2013_02_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2451 /g/paypal/paypal_2013_03_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2519  /g/paypal/paypal_2013_04_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2572  /g/paypal/paypal_2013_05_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2627  /g/paypal/paypal_2013_06_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2682  /g/paypal/paypal_2013_07_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2741 /g/paypal/paypal_2013_08_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2820 /g/paypal/paypal_2013_09_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2891 /g/paypal/paypal_2013_10_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 2973 /g/paypal/paypal_2013_11_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3040 /g/paypal/paypal_2013_12_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3094 /g/paypal/paypal_2014_01_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3163 /g/paypal/paypal_2014_02_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3205 /g/paypal/paypal_2014_03_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3251 /g/paypal/paypal_2014_04_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3297 /g/paypal/paypal_2014_05_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3351 /g/paypal/paypal_2014_06_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3413 --avoid_numbers '3450 3451' /g/paypal/paypal_2014_07_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3450 /g/paypal/virements_2014_07.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3475 /g/paypal/paypal_2014_08_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3538 /g/paypal/paypal_2014_09_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3614 /g/paypal/virements_2014_10.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3618 /g/paypal/paypal_2014_10_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3691 /g/paypal/paypal_2014_11_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan --write_invoices --first_in 3750 /g/paypal/paypal_2014_12_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 3809 /g/paypal/paypal_2015_01_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 3877 /g/paypal/paypal_2015_02_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 3957 /g/paypal/virements_2015_03.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 3959 /g/paypal/paypal_2015_03_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4031 /g/paypal/paypal_2015_04_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4085 /g/paypal/paypal_2015_05_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4139 /g/paypal/paypal_2015_06_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4196 /g/paypal/paypal_2015_07_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4263 /g/paypal/paypal_2015_08_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4317 /g/paypal/paypal_2015_09_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4383 /g/paypal/paypal_2015_10_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4451 /g/paypal/paypal_2015_11_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4506 /g/paypal/paypal_2015_12_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4575 /g/paypal/paypal_2016_01_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4642 /g/paypal/paypal_2016_02_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4695 /g/paypal/paypal_2016_03_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4776 /g/paypal/paypal_2016_04_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4860 /g/paypal/paypal_2016_05_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 4931 /g/paypal/paypal_2016_06_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5009 /g/paypal/paypal_2016_07_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5081 /g/paypal/paypal_2016_08_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5147 /g/paypal/paypal_2016_09_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5216 /g/paypal/paypal_2016_10_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5216 /g/paypal/paypal_2016_10_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5276 /g/paypal/paypal_2016_11_complet.csv
# Two bank transfer in 2016_12
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5355 /g/paypal/virements_2016_12_06.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5338 --avoid_numbers '5355' /g/paypal/paypal_2016_12_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5406 /g/paypal/virements_2016_12_31.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5407 /g/paypal/paypal_2017_01_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5490 /g/paypal/paypal_2017_02_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5558 /g/paypal/paypal_2017_03_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5651 /g/paypal/paypal_2017_04_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5714 /g/paypal/paypal_2017_05_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5780 /g/paypal/paypal_2017_06_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5833  /g/paypal/paypal_2017_07_complet.csv
#/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5903  /g/paypal/paypal_2017_08_complet.csv

set -x
/g/public_html/imapsync/W/paypal_reply/paypal_bilan  --write_invoices --first_in 5978  /g/paypal/paypal_2017_09_complet.csv



set +x


: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 147 /g/paypal/paypal_2010_11_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 214 /g/paypal/paypal_2010_12_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 294 --usdeur 1.3385 /g/paypal/paypal_2011_01_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 382 --usdeur 1.3692 /g/paypal/paypal_2011_02_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 473 --usdeur 1.3809 /g/paypal/paypal_2011_03_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 570 --usdeur 1.4172 /g/paypal/paypal_2011_04_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 645 --usdeur 1.4810 /g/paypal/paypal_2011_05_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 733 --usdeur 1.4395 /g/paypal/paypal_2011_06_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 824 --usdeur 1.4496 /g/paypal/paypal_2011_07_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 917 --usdeur 1.4397 /g/paypal/paypal_2011_08_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 999 --usdeur 1.4380 /g/paypal/paypal_2011_09_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1094 --usdeur 1.3387 /g/paypal/paypal_2011_10_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1185 --usdeur 1.3856 /g/paypal/paypal_2011_11_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1263 --usdeur 1.3438 /g/paypal/paypal_2011_12_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1335 --usdeur 1.2952 /g/paypal/paypal_2012_01_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1417 /g/paypal/paypal_2012_02_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1508 /g/paypal/paypal_2012_03_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1575 /g/paypal/paypal_2012_04_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1654 /g/paypal/paypal_2012_05_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1743 /g/paypal/paypal_2012_06_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1824 /g/paypal/paypal_2012_07_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1891 /g/paypal/paypal_2012_08_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 1963 /g/paypal/paypal_2012_09_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2047 /g/paypal/paypal_2012_10_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2133 /g/paypal/paypal_2012_11_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2224 /g/paypal/paypal_2012_12_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2299 /g/paypal/paypal_2013_01_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2384 /g/paypal/paypal_2013_02_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2451 /g/paypal/paypal_2013_03_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2519 /g/paypal/paypal_2013_04_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2572 /g/paypal/paypal_2013_05_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2627 /g/paypal/paypal_2013_06_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2682 /g/paypal/paypal_2013_07_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2741 /g/paypal/paypal_2013_08_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2820 /g/paypal/paypal_2013_09_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2891 /g/paypal/paypal_2013_10_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 2973 /g/paypal/paypal_2013_11_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3040 /g/paypal/paypal_2013_12_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3094 /g/paypal/paypal_2014_01_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3163 /g/paypal/paypal_2014_02_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3205 /g/paypal/paypal_2014_03_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3251 /g/paypal/paypal_2014_04_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3297 /g/paypal/paypal_2014_05_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3351 /g/paypal/paypal_2014_06_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3413 --avoid_numbers '3450 3451' /g/paypal/paypal_2014_07_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3450 /g/paypal/virements_2014_07.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3475 /g/paypal/paypal_2014_08_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3538 /g/paypal/paypal_2014_09_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3614 /g/paypal/virements_2014_10.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3618 /g/paypal/paypal_2014_10_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3691 /g/paypal/paypal_2014_11_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3750 /g/paypal/paypal_2014_12_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3809 /g/paypal/paypal_2015_01_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3877 /g/paypal/paypal_2015_02_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 3959 /g/paypal/paypal_2015_03_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4031 /g/paypal/paypal_2015_04_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4085 /g/paypal/paypal_2015_05_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4139 /g/paypal/paypal_2015_06_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4196 /g/paypal/paypal_2015_07_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4263 /g/paypal/paypal_2015_08_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4317 /g/paypal/paypal_2015_09_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4383 /g/paypal/paypal_2015_10_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4451 /g/paypal/paypal_2015_11_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4506 /g/paypal/paypal_2015_12_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4575 /g/paypal/paypal_2016_01_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4642 /g/paypal/paypal_2016_02_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4695 /g/paypal/paypal_2016_03_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4776 /g/paypal/paypal_2016_04_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4860 /g/paypal/paypal_2016_05_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 4931 /g/paypal/paypal_2016_06_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5009 /g/paypal/paypal_2016_07_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5081 /g/paypal/paypal_2016_08_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5147 /g/paypal/paypal_2016_09_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5216 /g/paypal/paypal_2016_10_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5276 /g/paypal/paypal_2016_11_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5355 /g/paypal/virements_2016_12_06.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5338 --avoid_numbers '5355' /g/paypal/paypal_2016_12_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5406 /g/paypal/virements_2016_12_31.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5407 /g/paypal/paypal_2017_01_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5490 /g/paypal/paypal_2017_02_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5558 /g/paypal/paypal_2017_03_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5651 /g/paypal/paypal_2017_04_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5714 /g/paypal/paypal_2017_05_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5780 /g/paypal/paypal_2017_06_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5833 /g/paypal/paypal_2017_07_complet.csv
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5903 /g/paypal/paypal_2017_08_complet.csv

set -x
# TVA a faire
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --first_in 5978 /g/paypal/paypal_2017_09_complet.csv
set +x

# La totale

: /g/public_html/imapsync/W/paypal_reply/paypal_bilan --bnc --debug \
  --first_in 147 --avoid_numbers '292 293  643 644 731 732 1093  
1330 1331 1332 1333 1334 1652 1653 2131 2132 
2295 2296 2297 2298 2625 2626 2970 2971 2972  
3093 3296 3411 3412 3450 3451 3614 3615 3616 3617
3807 3808 3957 3958 4030 4194 4195 4381 4382 4449 4450 
4574 4641 5213 5214 5215 5355 5406
5489 5650' \
  /g/paypal/paypal_201?_??_complet.csv

#set -v
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 147 --avoid_numbers '292 293  643 644 731 732 1093  
1330 1331 1332 1333 1334 1652 1653 2131 2132  
2295 2296 2297 2298 2625 2626 2970 2971 2972  
3093 3296 3411 3412 3450 3451 3614 3615 3616 3617
3807 3808 3957 3958 4030 4194 4195 4381 4382 4449 4450 
4574 4641 5213 5214 5215 5355 5406
5489 5650' \
  /g/paypal/paypal_201?_??_complet.csv
#set +v

#echo 2017 : ( from 5407 to ???? ) EUR 
#set -v
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 5407 --avoid_numbers '5489 5650' \
  /g/paypal/paypal_2017_??_complet.csv
#set +v


#echo 2016 : ( from 4574 to 5406 ) EUR 
#set -v
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 4575 --avoid_numbers '4574 4641 5213 5214 5215 5355 5406' \
  /g/paypal/paypal_2016_??_complet.csv
#set +v

#echo 2015 : ( from 3809 to 4573 ) EUR 
#set -v
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 3809 --avoid_numbers '3807 3808 3957 3958 4030 4194 4195 4381 4382 4449 4450' \
  /g/paypal/paypal_2015_??_complet.csv
#set +v

#echo 2014 : 704 ( from 3094 to 3806 ) EUR 36900.00
#set -v
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 3093 --avoid_numbers '3093 3296 3411 3412 3450 3451 3614 3615 3616 3617' \
  /g/paypal/paypal_2014_??_complet.csv
#set +v

#echo 2013 : 789 ( from 2299 to 3092 ) EUR 38652.00
#set -v
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 2299 --avoid_numbers '2625 2626 2970 2971 2972' \
  /g/paypal/paypal_2013_??_complet.csv
#set +v

#echo 2012 : 956 ( from 1335 to 2294 ) EUR 37872.00
#set -v
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 1335 --usdeur 1.2952 --avoid_numbers '1652 1653 2131 2132  2295 2296 2297 2298' \
  /g/paypal/paypal_2012_??_complet.csv
#set +v

# echo 2011 : 1031 ( from 294 to 1329 ) EUR 30983.02
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan \
  --first_in 292 --avoid_numbers '292 293  643 644 731 732 1093' \
  /g/paypal/paypal_2011_??_complet.csv


# echo 2010 : 145 ( from 147 to 291 ) EUR 3836.38
: /g/public_html/imapsync/W/paypal_reply/paypal_bilan   --first_in 147 --avoid_numbers '' /g/paypal/paypal_2010_??_complet.csv


echo 'sh paypal_build_invoices  /g/var/paypal_invoices/5???'

# USD de 147 a 340
# EUR de 341 a ...

# 20110413 Found problems with  189 199     249 258 263 359     537
# 20110412 Found problems with  189 199 242 249 258 263 359 382 537
#                               cen cen JAP cen cen cen cen TCH JAP
#                                       cen


for d in "$@"; do 
	echo "==== $d ===="
	cd $d
	bd=`basename $d`
	
	if ls SENT_TO_* 2>/dev/null ; then
		echo "!!! Already sent "
		continue
	fi
	
	rm -f facture_imapsync-$bd.tex
	cp -f ../facture_imapsync-000.tex facture_imapsync-$bd.tex
	
	if { ! pdflatex facture_imapsync-$bd.tex < /dev/null > /dev/null || test -f facture_imapsync-${bd}_good.tex ; } then
		echo "PB $bd"
		if test -f facture_imapsync-${bd}_good.tex \
                   && pdflatex facture_imapsync-${bd}_good.tex < /dev/null > /dev/null
                then
			ln -f facture_imapsync-${bd}_good.pdf facture_imapsync-$bd.pdf
			echo "PB $bd solved with manual facture_imapsync-${bd}_good.tex"
			PB_LIST_MANUAL="$PB_LIST_MANUAL $bd"
		else
			PB_LIST="$PB_LIST $bd"
			rm -f facture_imapsync-$bd.pdf
			continue		
		fi
	fi
	#gpg --use-agent --armor --detach-sign --yes facture_imapsync-$bd.pdf
done

echo "Found problems with $PB_LIST"
echo "Manual invoices for $PB_LIST_MANUAL"
