#!/bin/sh

# $Id: paypal_run_laposte,v 1.5 2012/08/24 14:18:02 gilles Exp gilles $

set -e
#set -x


# Add path to commands at home
PATH=$PATH:/g/public_html/imapsync/W/paypal_reply
PERL5LIB=/g/public_html/imapsync/Mail-IMAPClient-3.30/lib
export PERL5LIB

test -f /g/public_html/imapsync/W/paypal_reply/paypal_functions \
&& . /g/public_html/imapsync/W/paypal_reply/paypal_functions


DATE_1=`date`

echo "==== paypal_reply_laposte ===="
paypal_reply_laposte "$@"
echo



DATE_2=`date`

echo "Debut : $DATE_1" 
echo "Fin   : $DATE_2"
echo "Yo Bery GOOD !"
