# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-IMAPClient
version:      3.21
version_from: lib/Mail/IMAPClient.pm
installdirs:  site
requires:
    Carp:                          0
    Errno:                         0
    Fcntl:                         0
    File::Temp:                    0
    IO::File:                      0
    IO::Select:                    0
    IO::Socket:                    0
    IO::Socket::INET:              1.26
    List::Util:                    0
    MIME::Base64:                  0
    Parse::RecDescent:             1.94
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
