---
abstract: 'IMAP4 client library'
author:
  - 'Phil Pearl (Lobbes) <phil@zimbra.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-IMAPClient
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Errno: '0'
  Fcntl: '0'
  File::Temp: '0'
  IO::File: '0'
  IO::Select: '0'
  IO::Socket: '0'
  IO::Socket::INET: '1.26'
  List::Util: '0'
  MIME::Base64: '0'
  Parse::RecDescent: '1.94'
  Test::More: '0'
  perl: '5.008'
resources:
  homepage: http://sourceforge.net/projects/mail-imapclient/
version: '3.39'
