=head1 NAME

Mail::IMAPClient::BodyStructure::Parse - used internally by Mail::IMAPClient::BodyStructure

=head1 DESCRIPTION

This module is used internally by L<Mail::IMAPClient::BodyStructure>
and is generated using L<Parse::RecDescent>. It is not meant to be used
directly by other scripts nor is there much point in debugging it.

=head1 SYNOPSIS

This module is used internally by L<Mail::IMAPClient::BodyStructure>
and is not meant to be used or called directly from applications. So
don't do that.
