version: "3.8"
services:
  dovecot-source:
    image: dovecot/dovecot:2.3
    ports:
      - "10143:143"
    environment:
      - DOVECOT_PASSDB=pass:password1
  dovecot-dest:
    image: dovecot/dovecot:2.3
    ports:
      - "10144:143"
    environment:
      - DOVECOT_PASSDB=pass:password2
