#!/usr/bin/perl -w


use Mail::IMAPClient;

$imap = Mail::IMAPClient->new();
$imap->Debug(1);
$imap->Server('Xlouloutte.dyndns.org');
$imap->connect() or die;
$imap->User('MarkOv@est.belle');
$imap->Password('emhj91ly');
$imap->login();
$imap->logout();


