#!/bin/sh

# $Id: gen_README_dist,v 1.1 2014/05/29 23:33:19 gilles Exp gilles $

VERSION_UNX=`cat VERSION`
#echo $VERSION_UNX
VERSION_EXE=`cat VERSION_EXE`
#echo $VERSION_EXE

cat <<EOF 

imapsync-$VERSION_EXE.zip  is for Windows users.

imapsync-$VERSION_UNX.tgz  is for Unix and Mac users.

imapsync file script is for a fast upgrade on Unix (just download and install it).
EOF




