#!/bin/sh

# $Id: gen_README_dist,v 1.4 2020/01/04 09:16:08 gilles Exp gilles $


VERSION=`cat VERSION`
#echo $VERSION

cat <<EOF 

The file "imapsync-$VERSION.zip" is for Windows users.

The file "imapsync-$VERSION.tgz"  is for Unix and OS X users, it contains the source
code and also the standalone OS X binary named "imapsync_bin_Darwin".

The binary "imapsync_bin_Darwin" is for OS X users, as a shortcut for a fast upgrade.

The file "imapsync" is the source code perl script, it is there just for a fast 
upgrade on Unix, just download and replace the old one with this one.
Sometimes new Perl modules need to be installed, see
https://imapsync.lamiral.info/S/news.shtml

EOF




