#!/bin/sh

# $Id: gen_README_dist,v 1.2 2017/09/11 02:19:34 gilles Exp gilles $

VERSION_UNX=`cat VERSION`
#echo $VERSION_UNX
VERSION_EXE=`cat VERSION_EXE`
#echo $VERSION_EXE

cat <<EOF 

The file "imapsync-$VERSION_EXE.zip" is for Windows users.

The file "imapsync-$VERSION_UNX.tgz"  is for Unix and OS X users, it contains the source
code and also the standalone OS X binary named "imapsync_bin_Darwin".

The binary "imapsync_bin_Darwin" is for OS X users, as a shortcut for a fast upgrade.

The file "imapsync" is the source code perl script, it is there just for a fast 
upgrade on Unix, just download and replace the old one with this one.
Sometimes new Perl modules need to be installed, see
https://imapsync.lamiral.info/S/news.shtml

EOF




