#!/bin/sh

# $Id: imapsync_github_stats,v 1.3 2018/08/28 12:28:53 gilles Exp gilles $

get_csv() {

    ( 
    cd csv || return
    { sleep 1; cat /g/var/pass/secret.gilles_github; } | gts gilleslamiral imapsync save_csv  -o imapsync 
    sh ../merge-csv .
    )
}

PATH=$PATH:/g/bin
cd /g/public_html/imapsync/W/gts/
get_csv
rsync -av . /g/public_html/imapsync_github/gts/



